import os
from datetime import datetime
from typing import List, Dict


SOURCES_TEMPLATE = """---
title: {tool} - Sources
---

# {tool} — Top Sources

*Collected: {date}*

| # | Title | URL |
|---|-------|-----|
{table_rows}

## Annotated Sources

{annotated}
"""

INDEX_TEMPLATE = """---
title: Tool Research Index
---

# Tool Research Index

A living knowledge base of senior-engineer-level research on tools, frameworks, and infrastructure.

## Tools Covered

{tool_list}

---
*Generated by tool-researcher. Run `python main.py <toolname>` to add a new tool.*
"""


class WriterAgent:
    def __init__(self, docs_root: str):
        self.docs_root = docs_root

    def _tool_dir(self, tool: str) -> str:
        return os.path.join(self.docs_root, tool.lower())

    def tool_exists(self, tool: str) -> bool:
        return os.path.isdir(self._tool_dir(tool))

    def write(self, tool: str, sources: List[Dict], overview: str, examples: List[Dict]):
        tool_dir = self._tool_dir(tool)
        examples_dir = os.path.join(tool_dir, "examples")
        os.makedirs(examples_dir, exist_ok=True)

        # 1. overview → index.md
        self._write_file(os.path.join(tool_dir, "index.md"), overview)
        print(f"[Writer] Wrote {tool}/index.md")

        # 2. sources → sources.md
        sources_md = self._build_sources_md(tool, sources)
        self._write_file(os.path.join(tool_dir, "sources.md"), sources_md)
        print(f"[Writer] Wrote {tool}/sources.md")

        # 3. examples
        for ex in examples:
            filename = f"{ex['id']}.md"
            self._write_file(os.path.join(examples_dir, filename), ex["content"])
            print(f"[Writer] Wrote {tool}/examples/{filename}")

        # 4. Rebuild top-level index
        self._rebuild_index()
        print(f"[Writer] Rebuilt docs/index.md\n")

    def _write_file(self, path: str, content: str):
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    def _build_sources_md(self, tool: str, sources: List[Dict]) -> str:
        date = datetime.now().strftime("%Y-%m-%d")
        rows = []
        annotated = []

        for i, s in enumerate(sources, 1):
            title = s.get("title", "Untitled")
            url = s.get("url", "")
            rows.append(f"| {i} | {title} | [{url}]({url}) |")
            desc = s.get("description", "")[:300]
            annotated.append(f"### {i}. [{title}]({url})\n{desc}\n")

        return SOURCES_TEMPLATE.format(
            tool=tool,
            date=date,
            table_rows="\n".join(rows),
            annotated="\n".join(annotated),
        )

    def _rebuild_index(self):
        """Scan docs/ for tool folders and regenerate index.md."""
        tools = sorted([
            d for d in os.listdir(self.docs_root)
            if os.path.isdir(os.path.join(self.docs_root, d))
            and not d.startswith(".")
        ])

        tool_list_lines = []
        for t in tools:
            tool_list_lines.append(f"- [{t.upper()}](./{t}/index.md)")

        index_content = INDEX_TEMPLATE.format(
            tool_list="\n".join(tool_list_lines) if tool_list_lines else "_No tools yet._"
        )
        self._write_file(os.path.join(self.docs_root, "index.md"), index_content)
